root      ::= (commands eol)+
commands  ::= t | info | nav
nav       ::= "nav(\"/" [a-z/]*  "\")"
info      ::= "info(" setting ")"
t         ::= "t(" setting ": " value ")"
value     ::= color | number | string | boolean
color     ::= "#" [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]
setting   ::= [a-z_ ]+
string    ::= "\"" [ \t!#-\[\]-~#x80-#xFF]* "\""
number    ::= [0-9]+
boolean   ::= ("true" | "false")
eol       ::= "\n"
