name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install poetry
        sed -i 's/^torch =.*/torch = { url = "https:\/\/download.pytorch.org\/whl\/cpu\/torch-2.0.1%2Bcpu-cp311-cp311-linux_x86_64.whl" }/' pyproject.toml
        poetry install

    - name: Run black for code formatting
      run: |
        poetry run black --check .

    - name: Run ruff for style checks
      run: |
        poetry run ruff .

    - name: Run pytest for tests
      run: |
        poetry run pytest tests
