name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black

    - name: Run black for code formatting
      run: |
        black --check .

    - name: Run ruff for style checks
      run: |
        ruff --check .

    - name: Run pytest for tests
      run: |
        pytest tests
